// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuuwnehecvrtpjetakgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1dXduZWhlY3ZydHBqZXRha2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTg1MzcsImV4cCI6MjA3MTkzNDUzN30.1uW4RB4msvxKh_4vKsisg4uHmlj5V7unsKen40WtLGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});